namespace uwap.WebFramework.Plugins;

public partial class UsersPlugin
{
    public override byte[]? GetFile(string relPath, string pathPrefix, string domain)
        => relPath switch
        {
            "/auth-request.js" => (byte[]?)PackedFiles_ResourceManager.GetObject("File0"),
            "/fonts/roboto-mono.eot" => (byte[]?)PackedFiles_ResourceManager.GetObject("File1"),
            "/fonts/roboto-mono.otf" => (byte[]?)PackedFiles_ResourceManager.GetObject("File2"),
            "/fonts/roboto-mono.svg" => (byte[]?)PackedFiles_ResourceManager.GetObject("File3"),
            "/fonts/roboto-mono.ttf" => (byte[]?)PackedFiles_ResourceManager.GetObject("File4"),
            "/fonts/roboto-mono.woff" => (byte[]?)PackedFiles_ResourceManager.GetObject("File5"),
            "/fonts/roboto-mono.woff2" => (byte[]?)PackedFiles_ResourceManager.GetObject("File6"),
            "/fonts/roboto.eot" => (byte[]?)PackedFiles_ResourceManager.GetObject("File7"),
            "/fonts/roboto.otf" => (byte[]?)PackedFiles_ResourceManager.GetObject("File8"),
            "/fonts/roboto.svg" => (byte[]?)PackedFiles_ResourceManager.GetObject("File9"),
            "/fonts/roboto.ttf" => (byte[]?)PackedFiles_ResourceManager.GetObject("File10"),
            "/fonts/roboto.woff" => (byte[]?)PackedFiles_ResourceManager.GetObject("File11"),
            "/fonts/roboto.woff2" => (byte[]?)PackedFiles_ResourceManager.GetObject("File12"),
            "/fonts/special-elite.eot" => (byte[]?)PackedFiles_ResourceManager.GetObject("File13"),
            "/fonts/special-elite.otf" => (byte[]?)PackedFiles_ResourceManager.GetObject("File14"),
            "/fonts/special-elite.svg" => (byte[]?)PackedFiles_ResourceManager.GetObject("File15"),
            "/fonts/special-elite.ttf" => (byte[]?)PackedFiles_ResourceManager.GetObject("File16"),
            "/fonts/special-elite.woff" => (byte[]?)PackedFiles_ResourceManager.GetObject("File17"),
            "/fonts/special-elite.woff2" => (byte[]?)PackedFiles_ResourceManager.GetObject("File18"),
            "/fonts/ubuntu-mono.eot" => (byte[]?)PackedFiles_ResourceManager.GetObject("File19"),
            "/fonts/ubuntu-mono.otf" => (byte[]?)PackedFiles_ResourceManager.GetObject("File20"),
            "/fonts/ubuntu-mono.svg" => (byte[]?)PackedFiles_ResourceManager.GetObject("File21"),
            "/fonts/ubuntu-mono.ttf" => (byte[]?)PackedFiles_ResourceManager.GetObject("File22"),
            "/fonts/ubuntu-mono.woff" => (byte[]?)PackedFiles_ResourceManager.GetObject("File23"),
            "/fonts/ubuntu-mono.woff2" => (byte[]?)PackedFiles_ResourceManager.GetObject("File24"),
            "/fonts/ubuntu.eot" => (byte[]?)PackedFiles_ResourceManager.GetObject("File25"),
            "/fonts/ubuntu.otf" => (byte[]?)PackedFiles_ResourceManager.GetObject("File26"),
            "/fonts/ubuntu.svg" => (byte[]?)PackedFiles_ResourceManager.GetObject("File27"),
            "/fonts/ubuntu.ttf" => (byte[]?)PackedFiles_ResourceManager.GetObject("File28"),
            "/fonts/ubuntu.woff" => (byte[]?)PackedFiles_ResourceManager.GetObject("File29"),
            "/fonts/ubuntu.woff2" => (byte[]?)PackedFiles_ResourceManager.GetObject("File30"),
            "/settings/apps.js" => (byte[]?)PackedFiles_ResourceManager.GetObject("File31"),
            "/settings/theme.js" => (byte[]?)PackedFiles_ResourceManager.GetObject("File32"),
            "/theme/a/blue-dark.css" => (byte[]?)PackedFiles_ResourceManager.GetObject("File33"),
            "/theme/a/blue-light.css" => (byte[]?)PackedFiles_ResourceManager.GetObject("File34"),
            "/theme/a/green-dark.css" => (byte[]?)PackedFiles_ResourceManager.GetObject("File35"),
            "/theme/a/green-light.css" => (byte[]?)PackedFiles_ResourceManager.GetObject("File36"),
            "/theme/a/none-dark.css" => (byte[]?)PackedFiles_ResourceManager.GetObject("File37"),
            "/theme/a/none-light.css" => (byte[]?)PackedFiles_ResourceManager.GetObject("File38"),
            "/theme/a/red-dark.css" => (byte[]?)PackedFiles_ResourceManager.GetObject("File39"),
            "/theme/a/red-light.css" => (byte[]?)PackedFiles_ResourceManager.GetObject("File40"),
            "/theme/a/violet-dark.css" => (byte[]?)PackedFiles_ResourceManager.GetObject("File41"),
            "/theme/a/violet-light.css" => (byte[]?)PackedFiles_ResourceManager.GetObject("File42"),
            "/theme/b/beige.css" => (byte[]?)PackedFiles_ResourceManager.GetObject("File43"),
            "/theme/b/black.css" => (byte[]?)PackedFiles_ResourceManager.GetObject("File44"),
            "/theme/b/dark.css" => (byte[]?)PackedFiles_ResourceManager.GetObject("File45"),
            "/theme/b/light.css" => (byte[]?)PackedFiles_ResourceManager.GetObject("File46"),
            "/theme/b/white.css" => (byte[]?)PackedFiles_ResourceManager.GetObject("File47"),
            "/theme/base.css" => (byte[]?)PackedFiles_ResourceManager.GetObject("File48"),
            "/theme/d/flat.css" => (byte[]?)PackedFiles_ResourceManager.GetObject("File49"),
            "/theme/d/layers.css" => (byte[]?)PackedFiles_ResourceManager.GetObject("File50"),
            "/theme/d/shadows.css" => (byte[]?)PackedFiles_ResourceManager.GetObject("File51"),
            "/theme/f/roboto-mono.css" => System.Text.Encoding.UTF8.GetBytes($"@font-face {{\n    font-family: 'roboto-mono';\n    font-style: normal;\n    font-weight: 400;\n    font-display: block;\n    src: url('{pathPrefix}/fonts/roboto-mono.woff2') format('woff2'), url('{pathPrefix}/fonts/roboto-mono.woff') format('woff'), url('{pathPrefix}/fonts/roboto-mono.ttf') format('truetype'), url('{pathPrefix}/fonts/roboto-mono.otf') format('otf'), url('{pathPrefix}/fonts/roboto-mono.eot') format('embedded-opentype'), url('{pathPrefix}/fonts/roboto-mono.svg') format('svg');\n    unicode-range: U+000-5FF;\n    size-adjust: 85%;\n}}\n"),
            "/theme/f/roboto.css" => System.Text.Encoding.UTF8.GetBytes($"@font-face {{\n    font-family: 'roboto';\n    font-style: normal;\n    font-weight: 400;\n    font-display: block;\n    src: url('{pathPrefix}/fonts/roboto.woff2') format('woff2'), url('{pathPrefix}/fonts/roboto.woff') format('woff'), url('{pathPrefix}/fonts/roboto.ttf') format('truetype'), url('{pathPrefix}/fonts/roboto.otf') format('otf'), url('{pathPrefix}/fonts/roboto.eot') format('embedded-opentype'), url('{pathPrefix}/fonts/roboto.svg') format('svg');\n    unicode-range: U+000-5FF;\n    size-adjust: 95%;\n}}\n"),
            "/theme/f/special-elite.css" => System.Text.Encoding.UTF8.GetBytes($"@font-face {{\n    font-family: 'special-elite';\n    font-style: normal;\n    font-weight: 400;\n    font-display: block;\n    src: url('{pathPrefix}/fonts/special-elite.woff2') format('woff2'), url('{pathPrefix}/fonts/special-elite.woff') format('woff'), url('{pathPrefix}/fonts/special-elite.ttf') format('truetype'), url('{pathPrefix}/fonts/special-elite.otf') format('otf'), url('{pathPrefix}/fonts/special-elite.eot') format('embedded-opentype'), url('{pathPrefix}/fonts/special-elite.svg') format('svg');\n    unicode-range: U+000-5FF;\n    size-adjust: 102%;\n}}\n"),
            "/theme/f/ubuntu-mono.css" => System.Text.Encoding.UTF8.GetBytes($"@font-face {{\n    font-family: 'ubuntu-mono';\n    font-style: normal;\n    font-weight: 400;\n    font-display: block;\n    src: url('{pathPrefix}/fonts/ubuntu-mono.woff2') format('woff2'), url('{pathPrefix}/fonts/ubuntu-mono.woff') format('woff'), url('{pathPrefix}/fonts/ubuntu-mono.ttf') format('truetype'), url('{pathPrefix}/fonts/ubuntu-mono.otf') format('otf'), url('{pathPrefix}/fonts/ubuntu-mono.eot') format('embedded-opentype'), url('{pathPrefix}/fonts/ubuntu-mono.svg') format('svg');\n    unicode-range: U+000-5FF;\n    size-adjust: 101%;\n}}\n"),
            "/theme/f/ubuntu.css" => System.Text.Encoding.UTF8.GetBytes($"@font-face {{\n    font-family: 'ubuntu';\n    font-style: normal;\n    font-weight: 400;\n    font-display: block;\n    src: url('{pathPrefix}/fonts/ubuntu.woff2') format('woff2'), url('{pathPrefix}/fonts/ubuntu.woff') format('woff'), url('{pathPrefix}/fonts/ubuntu.ttf') format('truetype'), url('{pathPrefix}/fonts/ubuntu.otf') format('otf'), url('{pathPrefix}/fonts/ubuntu.eot') format('embedded-opentype'), url('{pathPrefix}/fonts/ubuntu.svg') format('svg');\n    unicode-range: U+000-5FF;\n}}\n"),
            "/users/user.js" => (byte[]?)PackedFiles_ResourceManager.GetObject("File52"),
            _ => null
        };
    
    public override string? GetFileVersion(string relPath)
        => relPath switch
        {
            "/auth-request.js" => "638581484028449854",
            "/fonts/roboto-mono.eot" => "638411470949411194",
            "/fonts/roboto-mono.otf" => "638411470949576421",
            "/fonts/roboto-mono.svg" => "638411470949788823",
            "/fonts/roboto-mono.ttf" => "638411470949939599",
            "/fonts/roboto-mono.woff" => "638411470950087365",
            "/fonts/roboto-mono.woff2" => "638411470950229264",
            "/fonts/roboto.eot" => "638411469495775983",
            "/fonts/roboto.otf" => "638411469495939369",
            "/fonts/roboto.svg" => "638411469496185143",
            "/fonts/roboto.ttf" => "638411469496350547",
            "/fonts/roboto.woff" => "638411469496497472",
            "/fonts/roboto.woff2" => "638411469496635695",
            "/fonts/special-elite.eot" => "638431795370000000",
            "/fonts/special-elite.otf" => "638431795370000000",
            "/fonts/special-elite.svg" => "638431795370000000",
            "/fonts/special-elite.ttf" => "638431795370000000",
            "/fonts/special-elite.woff" => "638431795370000000",
            "/fonts/special-elite.woff2" => "638431795370000000",
            "/fonts/ubuntu-mono.eot" => "638396347130000000",
            "/fonts/ubuntu-mono.otf" => "638396347130000000",
            "/fonts/ubuntu-mono.svg" => "638396347130000000",
            "/fonts/ubuntu-mono.ttf" => "638396347130000000",
            "/fonts/ubuntu-mono.woff" => "638396347130000000",
            "/fonts/ubuntu-mono.woff2" => "638396347130000000",
            "/fonts/ubuntu.eot" => "638396347130000000",
            "/fonts/ubuntu.otf" => "638396347130000000",
            "/fonts/ubuntu.svg" => "638396347130000000",
            "/fonts/ubuntu.ttf" => "638396347130000000",
            "/fonts/ubuntu.woff" => "638396347130000000",
            "/fonts/ubuntu.woff2" => "638396347130000000",
            "/settings/apps.js" => "638550400163890131",
            "/settings/theme.js" => "638550323510598042",
            "/theme/a/blue-dark.css" => "638409345494219633",
            "/theme/a/blue-light.css" => "638409323479535394",
            "/theme/a/green-dark.css" => "638409320369317625",
            "/theme/a/green-light.css" => "638409346342444667",
            "/theme/a/none-dark.css" => "638431127351526354",
            "/theme/a/none-light.css" => "638431127351526354",
            "/theme/a/red-dark.css" => "638409355393188496",
            "/theme/a/red-light.css" => "638409349568528784",
            "/theme/a/violet-dark.css" => "638409320949773236",
            "/theme/a/violet-light.css" => "638409325056622515",
            "/theme/b/beige.css" => "638431087090597956",
            "/theme/b/black.css" => "638409480772043904",
            "/theme/b/dark.css" => "638409494781574474",
            "/theme/b/light.css" => "638409498007323872",
            "/theme/b/white.css" => "638409498541666478",
            "/theme/base.css" => "638724751859600853",
            "/theme/d/flat.css" => "638724029336305363",
            "/theme/d/layers.css" => "638724029278504703",
            "/theme/d/shadows.css" => "638724029378205842",
            "/theme/f/roboto-mono.css" => "638548427731984066",
            "/theme/f/roboto.css" => "638548427774651087",
            "/theme/f/special-elite.css" => "638548427797751278",
            "/theme/f/ubuntu-mono.css" => "638548427823551492",
            "/theme/f/ubuntu.css" => "638548427912152227",
            "/users/user.js" => "638550451651615301",
            _ => null
        };
    
    private static readonly System.Resources.ResourceManager PackedFiles_ResourceManager = new("UsersPlugin.Properties.PackedFiles", typeof(UsersPlugin).Assembly);
}
