//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsersPluginBeta.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PluginFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PluginFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UsersPluginBeta.Properties.PluginFiles", typeof(PluginFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] L2ZvbnRzL3JvYm90by1tb25vLm90Zg {
            get {
                object obj = ResourceManager.GetObject("L2ZvbnRzL3JvYm90by1tb25vLm90Zg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] L2ZvbnRzL3JvYm90by1tb25vLmVvdA {
            get {
                object obj = ResourceManager.GetObject("L2ZvbnRzL3JvYm90by1tb25vLmVvdA", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] L2ZvbnRzL3JvYm90by1tb25vLndvZmY {
            get {
                object obj = ResourceManager.GetObject("L2ZvbnRzL3JvYm90by1tb25vLndvZmY", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] L2ZvbnRzL3JvYm90by1tb25vLndvZmYy {
            get {
                object obj = ResourceManager.GetObject("L2ZvbnRzL3JvYm90by1tb25vLndvZmYy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] L2ZvbnRzL3JvYm90by1tb25vLnN2Zw {
            get {
                object obj = ResourceManager.GetObject("L2ZvbnRzL3JvYm90by1tb25vLnN2Zw", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] L2ZvbnRzL3JvYm90by1tb25vLnR0Zg {
            get {
                object obj = ResourceManager.GetObject("L2ZvbnRzL3JvYm90by1tb25vLnR0Zg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] L2ZvbnRzL3JvYm90by50dGY {
            get {
                object obj = ResourceManager.GetObject("L2ZvbnRzL3JvYm90by50dGY", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] L2ZvbnRzL3JvYm90by53b2Zm {
            get {
                object obj = ResourceManager.GetObject("L2ZvbnRzL3JvYm90by53b2Zm", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] L2ZvbnRzL3JvYm90by53b2ZmMg {
            get {
                object obj = ResourceManager.GetObject("L2ZvbnRzL3JvYm90by53b2ZmMg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] L2ZvbnRzL3JvYm90by5lb3Q {
            get {
                object obj = ResourceManager.GetObject("L2ZvbnRzL3JvYm90by5lb3Q", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] L2ZvbnRzL3JvYm90by5vdGY {
            get {
                object obj = ResourceManager.GetObject("L2ZvbnRzL3JvYm90by5vdGY", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] L2ZvbnRzL3JvYm90by5zdmc {
            get {
                object obj = ResourceManager.GetObject("L2ZvbnRzL3JvYm90by5zdmc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] L2ZvbnRzL3NwZWNpYWwtZWxpdGUub3Rm {
            get {
                object obj = ResourceManager.GetObject("L2ZvbnRzL3NwZWNpYWwtZWxpdGUub3Rm", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] L2ZvbnRzL3NwZWNpYWwtZWxpdGUuc3Zn {
            get {
                object obj = ResourceManager.GetObject("L2ZvbnRzL3NwZWNpYWwtZWxpdGUuc3Zn", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] L2ZvbnRzL3NwZWNpYWwtZWxpdGUud29mZg {
            get {
                object obj = ResourceManager.GetObject("L2ZvbnRzL3NwZWNpYWwtZWxpdGUud29mZg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] L2ZvbnRzL3NwZWNpYWwtZWxpdGUud29mZjI {
            get {
                object obj = ResourceManager.GetObject("L2ZvbnRzL3NwZWNpYWwtZWxpdGUud29mZjI", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] L2ZvbnRzL3NwZWNpYWwtZWxpdGUudHRm {
            get {
                object obj = ResourceManager.GetObject("L2ZvbnRzL3NwZWNpYWwtZWxpdGUudHRm", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] L2ZvbnRzL3NwZWNpYWwtZWxpdGUuZW90 {
            get {
                object obj = ResourceManager.GetObject("L2ZvbnRzL3NwZWNpYWwtZWxpdGUuZW90", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] L2ZvbnRzL3VidW50dS1tb25vLm90Zg {
            get {
                object obj = ResourceManager.GetObject("L2ZvbnRzL3VidW50dS1tb25vLm90Zg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] L2ZvbnRzL3VidW50dS1tb25vLmVvdA {
            get {
                object obj = ResourceManager.GetObject("L2ZvbnRzL3VidW50dS1tb25vLmVvdA", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] L2ZvbnRzL3VidW50dS1tb25vLndvZmY {
            get {
                object obj = ResourceManager.GetObject("L2ZvbnRzL3VidW50dS1tb25vLndvZmY", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] L2ZvbnRzL3VidW50dS1tb25vLndvZmYy {
            get {
                object obj = ResourceManager.GetObject("L2ZvbnRzL3VidW50dS1tb25vLndvZmYy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] L2ZvbnRzL3VidW50dS1tb25vLnN2Zw {
            get {
                object obj = ResourceManager.GetObject("L2ZvbnRzL3VidW50dS1tb25vLnN2Zw", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] L2ZvbnRzL3VidW50dS1tb25vLnR0Zg {
            get {
                object obj = ResourceManager.GetObject("L2ZvbnRzL3VidW50dS1tb25vLnR0Zg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] L2ZvbnRzL3VidW50dS50dGY {
            get {
                object obj = ResourceManager.GetObject("L2ZvbnRzL3VidW50dS50dGY", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] L2ZvbnRzL3VidW50dS53b2Zm {
            get {
                object obj = ResourceManager.GetObject("L2ZvbnRzL3VidW50dS53b2Zm", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] L2ZvbnRzL3VidW50dS53b2ZmMg {
            get {
                object obj = ResourceManager.GetObject("L2ZvbnRzL3VidW50dS53b2ZmMg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] L2ZvbnRzL3VidW50dS5lb3Q {
            get {
                object obj = ResourceManager.GetObject("L2ZvbnRzL3VidW50dS5lb3Q", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] L2ZvbnRzL3VidW50dS5vdGY {
            get {
                object obj = ResourceManager.GetObject("L2ZvbnRzL3VidW50dS5vdGY", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] L2ZvbnRzL3VidW50dS5zdmc {
            get {
                object obj = ResourceManager.GetObject("L2ZvbnRzL3VidW50dS5zdmc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] L3RoZW1lL2Evbm9uZS1kYXJrLmNzcw {
            get {
                object obj = ResourceManager.GetObject("L3RoZW1lL2Evbm9uZS1kYXJrLmNzcw", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] L3RoZW1lL2Evbm9uZS1saWdodC5jc3M {
            get {
                object obj = ResourceManager.GetObject("L3RoZW1lL2Evbm9uZS1saWdodC5jc3M", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] L3RoZW1lL2EvcmVkLWRhcmsuY3Nz {
            get {
                object obj = ResourceManager.GetObject("L3RoZW1lL2EvcmVkLWRhcmsuY3Nz", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] L3RoZW1lL2EvcmVkLWxpZ2h0LmNzcw {
            get {
                object obj = ResourceManager.GetObject("L3RoZW1lL2EvcmVkLWxpZ2h0LmNzcw", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] L3RoZW1lL2EvdmlvbGV0LWRhcmsuY3Nz {
            get {
                object obj = ResourceManager.GetObject("L3RoZW1lL2EvdmlvbGV0LWRhcmsuY3Nz", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] L3RoZW1lL2EvdmlvbGV0LWxpZ2h0LmNzcw {
            get {
                object obj = ResourceManager.GetObject("L3RoZW1lL2EvdmlvbGV0LWxpZ2h0LmNzcw", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] L3RoZW1lL2EvYmx1ZS1kYXJrLmNzcw {
            get {
                object obj = ResourceManager.GetObject("L3RoZW1lL2EvYmx1ZS1kYXJrLmNzcw", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] L3RoZW1lL2EvYmx1ZS1saWdodC5jc3M {
            get {
                object obj = ResourceManager.GetObject("L3RoZW1lL2EvYmx1ZS1saWdodC5jc3M", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] L3RoZW1lL2EvZ3JlZW4tbGlnaHQuY3Nz {
            get {
                object obj = ResourceManager.GetObject("L3RoZW1lL2EvZ3JlZW4tbGlnaHQuY3Nz", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] L3RoZW1lL2EvZ3JlZW4tZGFyay5jc3M {
            get {
                object obj = ResourceManager.GetObject("L3RoZW1lL2EvZ3JlZW4tZGFyay5jc3M", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] L3RoZW1lL2IvbGlnaHQuY3Nz {
            get {
                object obj = ResourceManager.GetObject("L3RoZW1lL2IvbGlnaHQuY3Nz", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] L3RoZW1lL2Ivd2hpdGUuY3Nz {
            get {
                object obj = ResourceManager.GetObject("L3RoZW1lL2Ivd2hpdGUuY3Nz", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] L3RoZW1lL2IvYmVpZ2UuY3Nz {
            get {
                object obj = ResourceManager.GetObject("L3RoZW1lL2IvYmVpZ2UuY3Nz", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] L3RoZW1lL2IvYmxhY2suY3Nz {
            get {
                object obj = ResourceManager.GetObject("L3RoZW1lL2IvYmxhY2suY3Nz", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] L3RoZW1lL2IvZGFyay5jc3M {
            get {
                object obj = ResourceManager.GetObject("L3RoZW1lL2IvZGFyay5jc3M", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] L3RoZW1lL2QvbGF5ZXJzLmNzcw {
            get {
                object obj = ResourceManager.GetObject("L3RoZW1lL2QvbGF5ZXJzLmNzcw", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] L3RoZW1lL2Qvc2hhZG93cy5jc3M {
            get {
                object obj = ResourceManager.GetObject("L3RoZW1lL2Qvc2hhZG93cy5jc3M", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] L3RoZW1lL2QvZmxhdC5jc3M {
            get {
                object obj = ResourceManager.GetObject("L3RoZW1lL2QvZmxhdC5jc3M", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
